appServerAddr: "http://localhost:8081"
server:
  addr: ":8080"
  readTimeout: 1000
  writeTimeout: 1000
cache:
  inMemory: true
  redis:
    addr: localhost:6379
    username: ""
    password: ""
    db: 0
algorithm:
  name: fixed-window-count
  options:
    # Fixed Window Count Options
    windowLengthInSeconds: 60
    # Another Algorithm Options..
defaultRuleScope: path # todo ?
rules:
  - scope: rule
    pattern: "GET /xyz.*"
    limit: 3
  - scope: path
    pattern: "/xyz/a"
    limit: 5
  - scope: path
    pattern: "/abc"
    windowLengthInSeconds: 30
    limit: 4
tracing:
  enabled: false
  provider: new-relic
  newRelic:
    appName: appName
    licenseKey: licenseKey
    distributedTracerEnabled: true
