serverAddr: ":8080"
appServerAddr: "http://localhost:8081"
redis:
  addr: localhost:6379
  username: ""
  password: ""
  db: 0
rules:
  - pattern: "/xyz"
    limit: 3
  - pattern: "/abc"
    limit: 4
