server:
  addr: ":8080"
  readTimeout: 1000
  writeTimeout: 1000
appServerAddr: "http://localhost:8081"
cacheConfig:
  inMemory: true
  redis:
    addr: localhost:6379
    username: ""
    password: ""
    db: 0
rules:
  - pattern: "/xyz"
    limit: 3
  - pattern: "/abc"
    limit: 4
