appServerAddr: "http://localhost:8081"
server:
  addr: ":8080"
  readTimeout: 1000
  writeTimeout: 1000
cache:
  inMemory: true
  redis:
    addr: localhost:6379
    username: ""
    password: ""
    db: 0
rules:
  - pattern: "GET_/xyz.*"
    limit: 3
  - pattern: "/xyz/a"
    limit: 5
  - pattern: "/abc"
    limit: 4
